### ISSUE TITLE
magnet conversions on IPS_window

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#11]
It crossed my mind today that the IPS_window driver has some amp->tesla conversions hardcoded in it. If we want to start running all of our code out of this repository, we need to make some changes to IPS_window to handle this.

@Chrede88 I think you wrote it.

**Comment by Chrede88** [comment]
As far as I know this number is set in InitMagnet() and is not hardcoded in the code it self. If you believe this is a problem, I can of coarse take a look at it.

**Comment by FolkLab** [comment]
Yeah. That's right. Let's do this... leave a comment in InitMagnet() that contains the conversions for each of our magnets. Then, print a warning to the terminal with a reminder to check the value.

**Comment by Chrede88** [comment]
👍

**Comment by Chrede88** [comment]
Fixed! Pull request "IPS".
