### ISSUE TITLE
lakeshore window errors

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#12]
The lakeshore driver creates some elements of its window in the wrong place. @Chrede88 This one is you again, I think.

**Comment by Chrede88** [comment]
@nikhartman can you try run the initlakeshore in debug mode (run it line by line). Maybe this will gives us a hint as to what causes this problem.

**Comment by nikhartman** [comment]
At some point, yes. But don't wait for me.

**Comment by Chrede88** [comment]
Sure thing. We need to run it on a computer that's actually connected to a lakeshore. The init process collects a huge amount of info from the lakeshore.

**Comment by FolkLab** [comment]
This problem still exists in the most recent commit. A bunch of garbage popped up on my ScanController window. 

I will investigate more carefully sometime in the next two days.

**Comment by Chrede88** [comment]
Fixed in pull request #18
