### ISSUE TITLE
change labels on plots when starting new scan

### ISSUE THREAD

**Issue by FolkLab** [folk-lab/IgorAcq#13]
A while back, I added x_label and y_label tags to the InitializeWaves() function in ScanController(). It looks like @Chrede88 took the trouble to have these labels appear on the Igor plots as well, which I really like. However, if you run two scans back to back without closing the plot windows in between, the x_labels and y_labels do not change accordingly. 

Can we have these update every time InitializeWaves() is called?

**Comment by Chrede88** [comment]
Fixed it! Will add it to my current IPS branch.

**Comment by Chrede88** [comment]
Fixed it! See pull request "IPS".
