### ISSUE TITLE
babydac ADC readings incorrect

### ISSUE THREAD

**Issue by FolkLab** [folk-lab/IgorAcq#16]
Using the box that contains babyDAC 5 and 6, I get the correct readings from the ADCs on board 6 but the readings on board 5 are 10x what is expected.

Not sure yet if this is a hardware or software issue. If it is a software issue... god help us. There are a lot of binary commands to sort through.

**Comment by nikhartman** [comment]
The readings are not incorrect. There is an amplifier with a gain of 10 in there. I don't know why. And I certainly don't know why it isn't labelled. 

I labelled it.
