### ISSUE TITLE
time averaging

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#32]
Ebrahim brought up an interesting idea, to add a 'time averaging' flag to `RecordValues()` in ScanController. 

For example, you have the default would be `RecordValues(...., `timeavg = -1)', in which case each call runs as it does now, executing the measurement code just once after `delay`.

If you call `RecordValues(...., `timeavg = 10), a loop will be run for 10s in which the measurement code will be executed repeatedly with `delay` in between. The average value of this will be put into the waves created by InitWaves() and the time series data will be deleted.

That is all easy to implement in ScanController. The harder part is what to do about the plotting. I think you would want to see, but not record, each time series, as the measurement is running. So whatever dummy waves are created by `RecordValues()` should be plotted, if the `plot` option is selected in the ScanController window.

I'm going to implement the ScanController part of this without plotting. Maybe @Chrede88 can help with the plotting part once the ScanController thing works.

**Comment by Chrede88** [comment]
Sure! That sounds like a nice feature👍 Just let me know when it's running and I will look at the plotting side.

**Comment by nikhartman** [comment]
This works! The plotting actually turned out to be the easy part. Checkout the timeavg branch.

**Comment by nikhartman** [comment]
The timeavg does work. The only problem with it now is that it is not saving all the .winf files correctly.

I opened a second branch, timeavg2d, that will attempt to save data a little more concisely.

**Comment by Chrede88** [comment]
👍
