### ISSUE TITLE
update button on scan controller saves current configuration

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#36]
Running `InitScanController()` in the middle of an experiment can erase your current ScanController setup. Not a huge deal, but kind of a bummer. 

We could have the "Update" button save a configuration file, which can be read when `InitScanController()` is called. If there is no file, then load the defaults.

**Comment by Chrede88** [comment]
Sure, that's properly possible. An easier thing to do (but also a little more limited) is just to use any exciting waves that holds your setup config. This will mean that you can re-init the scancontroller without losing your setup.

**Comment by Chrede88** [comment]
Why are you calling initscancontroller() in the first place?

**Comment by nikhartman** [comment]
For example, if I want to pull some new code from this repository. I have to close Igor, fetch the code, and reopen Igor. At that point, I need to reinitialize all of my instruments. It is much easier to use `InitExp()` than to go through and figure out what I need to restart.

**Comment by Chrede88** [comment]
I see.
How about:
If there is a config file in the same directory as the experiment, calling initscancontroller() will use that otherwise it will use a default setup.

**Comment by nikhartman** [comment]
I think that is exactly what I had in mind. 

Bonus: You will end up saving some configuration information that might otherwise lose.

**Comment by Chrede88** [comment]
See pull request #37
