### ISSUE TITLE
babydac ramprates

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#40]
I tested this just now...

`noupdate = 0`: 100mV/s is really 62.4mV/s
`noupdate = 1`: 100mV/s is really 12.5mV/s

They scale linearly. Might be worth digging into this a little more.

**Comment by Chrede88** [comment]
Is the numbers per channel? The ramprates are defined by some sleep time, that most have been more or less correct when it was written. This method is in general pretty sloppy! I know that the DACs in CPH could be programmed to sweep at a rate controlled by the day board itself. The boards are build by the same guy from Harvard, so maybe our boards have the same functionalities.

**Comment by Chrede88** [comment]
Of coarse setting the sweep rate internally requires an extra request, which for the DAC boards are quite expensive (in terms of time). I'll take a look at the manual tomorrow.

**Comment by nikhartman** [comment]
Those times I quoted are for ramping just one channel.

The extra request shouldn't be a problem. As it is written now it takes at
least two requests per ramp (going from V1 to V2... set (V1+V2)/2, set V2).
If anything, I think setting a setpoint, then a ramprate will require fewer
requests than the current method, in most cases.

Good luck with that manual. The only one we have (at least on the Folk Lab
wiki) is a Word document written like 15 years ago.

Honestly, I'm fine with just tweeking the sleep times in the existing code.
It is pretty rare that we need an exact sweep rate. I'd settle for within a
factor of 2.

**Comment by Chrede88** [comment]
I just looked in the manual, it seems to be possible. It requires three calls, one to set the slope of the ramp, one to set the limit (where the ramp should stop) and one to initiate the ramp.

**Comment by Chrede88** [comment]
I think the best solution, for now, is just to change the wait times so they are more or less correct!
