### ISSUE TITLE
babydac wave scaling

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#45]
I find this a little confusing to work with. Let me try to explain why....

I have a voltage divider (1/5) on `CH1`. I run `ScanBabyDAC(-500,-400, "1", ....)`, which is dat11. Now, I want to set up dat12 based on the plots from dat11 that are still on screen. Those plots are scaled -100 to -80mV. So, when setting up the next scan, I have to rescale everything in my head. 

What would be better, I think, is to have the values on the plots always display in DAC output mV. And have all _saved_ waves in real mV seen by the sample. That way all of your analysis is done in real mV, but all of your experiment control is done in DAC output mV.

@Chrede88 thoughts?

**Comment by nikhartman** [comment]
I think I might be convinced that Josh's dummy instrument plan is the better one here. I think I would get a lot of use out of that feature.

**Comment by Chrede88** [comment]
So you would use to the dummy instruments to scale to the real dac output, right?
Lets say you want to sweep from -80mV to -100mV in sample units, the dummy instrument would rescale to -400mV and -500mV (assuming a 1/5 divider).

Doing this will keep the waves scaled to the sample units throughout Igor. I like the idea, but I think it's sometimes very useful to have the actual dac outputs somewhere (easily accessible). Maybe the dac window should have both values and the scale column?

**Comment by Chrede88** [comment]
I think we should also scale the limits in the dac window to sample units.

**Comment by Chrede88** [comment]
Issue resolved by implementation of the custom BabyDAC window.
