### ISSUE TITLE
construct_calc_script() in ScanController fails if script contains other calc wave name

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#54]
<img width="663" alt="screen shot 2018-04-29 at 7 34 47 pm" src="https://user-images.githubusercontent.com/2700867/39413786-6ac14aa6-4be4-11e8-9ca7-64ce313f4c70.png">

This throws an error because `current` is not turned into `current[i]`.

@Chrede88 you agree this should be fixed? Or did you have some reason for doing it this way?

**Comment by Chrede88** [comment]
No, this will fail! My implementation only looks at RawWavesNames for waves.
Standby!

**Comment by Chrede88** [comment]
See #55
