### ISSUE TITLE
config file for lab-specific information

### ISSUE THREAD

**Issue by FolkLab** [folk-lab/IgorAcq#57]
Here's the idea...

Move all Folk lab specific information out of scan controller and into a config file that lives in the master branch on github and can be read by Igor from there.

This would contain things like...

1. address of server
2. github address for webhooks
3. list of magnets
4. instrument specific communication information, such as commands and responses to test instruments, and serial port attributes that need to loaded for read/write to work correctly.

@Chrede88 The more I look at it, the more I like this idea.

**Comment by nikhartman** [comment]
I like this file format for a config file: https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

It's a classic. We'd have something like....

```
[labserver]
# this section sets up interactions with the lab server
# comments are pound signs
; or semi-colons
; but they have to appear at the beginning of the line
address=qdash-server.phas.ubc.ca
ftp_port=9999
push_data=0

[instrument]
name=babyDAC
varname=bd4
visa_address=ASRL4::INSTR
baud_rate=9600

[instrument]
name=SRS
varname=srs2
visa_address=GPIB::2::INSTR
```

**Comment by Chrede88** [comment]
That seems nice. Any reason for picking that format? I can be read by other programs, do we need that?

**Comment by nikhartman** [comment]
I just didn’t want to invent a new format. I assumed some smart people had
a good idea already. And this one seemed to fit. Even Igor itself has a
.ini config file. Maybe there is another secret function to read it.

**Comment by Chrede88** [comment]
I guess there must be😉👍

**Comment by Chrede88** [comment]
I started coding this today.  
Got a question that we need to agree on:  
How are we going to make sure the correct strings/variables are created/updated for the server? Are we going to define a list of keys that's allowed, like: "srv_push, server_url, ftp_port" and ignore keys that doesn't match and raise an error if not all keys are updated?  
Another way is to trust the keys and build global variables/strings based on the keys. This is easier, but more risky!  
Same question for the instruments. If we make a list, we also have to define some optional keys like "baud_rate,start_bits,stop_bits,parity".

**Comment by Chrede88** [comment]
I like the pre-defined list of accepted keys!  
This also makes the optional keys easier to handle. We can just define a function for opening a `GPIB` instrument and one for opening a `serial` instrument, with some optional arguments.  

`function openGPIB(instrID,adresse)` and `openSerial(instrID,adresse,[optional])`

**Comment by nikhartman** [comment]
Agreed. Predefined list of keys is definitely the better way to do it. We
can just make a generic config file with everything commented out in each
section and people can comment/uncomment the keys they need in their own
version.

**Comment by Chrede88** [comment]
:+1:  
I'm still in favour of doing some key checking, people do all kinds of strange things!

**Comment by nikhartman** [comment]
Yeah. It might be good enough just to dump any keys that aren't recognized and print a warning. Then abort on any missing-but-necessary keys.

**Comment by Chrede88** [comment]
Yep!

**Comment by nikhartman** [comment]
You should pull all those changes we just made into your `ini` branch. Otherwise you'll have a hell of a mess on your hands.

**Comment by Chrede88** [comment]
Just did!:)

**Comment by Chrede88** [comment]
How should we handle the new path needed here!? If the `setup.ini` file lives in the `igoracq` folder, we need to point to it. We can do it like `data` or maybe some other method?

**Comment by nikhartman** [comment]
I would say every experiment gets its own config. And we have a generic one
with everything commented out in the IgorAqc folder. Copy and paste as
needed.

**Comment by Chrede88** [comment]
So the `setup.ini` have to be on the data path then! I'm okay with that:)

**Comment by nikhartman** [comment]
Yeah. I think that is much easier. Then you never chance what is in this
repo.

**Comment by nikhartman** [comment]
I think this is done?

It still might be worth putting magnet/fridge information into some easily edited files, but that seems like a new issue. I'm not really interested in creating new work right now.

**Comment by Chrede88** [comment]
Yep! Found a few mistakes in your commit, really nothing huge. Will show you tomorrow.
And I agree, let’s put that off for some time.
