### ISSUE TITLE
Possible Speed up

### ISSUE THREAD

**Issue by roeetal** [folk-lab/IgorAcq#59]
https://github.com/folk-lab/IgorAcq/blob/78acd6f5b58aed7f9de9d204f9264fa424ee3422/ScanController_v2.0.ipf#L1411

I am thinking, since there is usually a sleep or delay between read calls, maybe duplicating the data folder for how ever many threads there will be **first**, before creating the threads, will make the async reads overhead a bit faster, and then the extra time used to create the data folders can be "incorporated" in the sleep between read calls?

**Comment by FolkLab** [comment]
That might be right. Although, there is some subtlety to the way that data folders are put into and read out of the thread queue. 

I suspect you are right though, that opening them all at once will not break anything and be at least a little faster. I'm not totally sure how to fit that inside of a sleep function, but I'll give it some thought.

**Comment by Chrede88** [comment]
Let's just close this one for now.
