### ISSUE TITLE
these damn check boxes

### ISSUE THREAD

**Issue by FolkLab** [folk-lab/IgorAcq#60]
<img width="658" alt="screen shot 2018-05-07 at 5 00 29 pm" src="https://user-images.githubusercontent.com/20827913/39730813-a8c4dbbc-5218-11e8-814f-2c0b6a80e878.png">

They pop up onto random windows because of the way that I update the ScanController window Async checkboxes after editing the `sc_measAsync` wave in `sc_findAsyncMeasurements()`. Not sure how to stop that from happening. But it would be great if we could figure it out.

**Comment by Chrede88** [comment]
I'm pretty sure it would be fixed if you add the following to the checkbox call:
`win=ScanController`

**Comment by FolkLab** [comment]
Yeeeesssssssss. That was it. Fixed.
