### ISSUE TITLE
Lakeshore 370 driver and auth tokens

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#64]
The LS370 driver now works:)
For now it has my auth token hard corded into the driver. What's your thought on that?
Clearly Ovi wants us to have individual tokens, but that's yet another thing people have to remember.

Also, the driver isn't setup to work with an `instrID`. I think we should change that, it's just not clear to me what this `instrID` should be. It can be the base url, but that's long and not easy to remember.
Another option is to use a string "name", but for that to work we need to set up rules for the naming scheme --> not optimal.

Any ideas?

**Comment by Chrede88** [comment]
Well! The `instrID` could your personal token! I kind of like that. Then the test function could call the `get-my=credentials` method, which returns the name and access level of the person associated with that token.

**Comment by nikhartman** [comment]
What does the token do? Does it restrict access somehow?

**Comment by nikhartman** [comment]
Slightly off topic: I'm pretty sure all the HTTP request functions in IGOR are threadsafe (along with FTP and pretty much every internet-based request). You should update those so they can be used used in async queries.

**Comment by Chrede88** [comment]
If you don’t send the a valid token, you are refund access.
I see, will update the relevant get functions to threadsafe versions.

**Comment by Chrede88** [comment]
Going back to the question about `InstrID` for the Lakeshore. Currently we are only accepting `variable` InstrID's. All the relevant things I can come up with for an `InstrID` are `strings`! Do we want to add that possibility to the code?

And if yes, are you onboard with using the `auth token` as `InstrID`?

**Comment by nikhartman** [comment]
Just caught up with your conversation on Gitea. Seems like you and Ovi can sort this out. Let me know what happens.
