### ISSUE TITLE
config files and JSON

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#70]
There is a bug in the config file loading functionality.  
A script with `"` characters will not load correctly.  
`getLS370temp("mc",max_age=10)` will load as `getLS370temp(`

**Comment by nikhartman** [comment]
That's the same problem I found before! Shiiiiiiiiit. I'll check it out.

**Comment by Chrede88** [comment]
Just tried to track the error. It happens in `readJSONstring`. This function assumes that the string only contain one `"` pair!

**Comment by Chrede88** [comment]
Here's how far I've got so far.  

This will code will fix any "non-escaped" `"`:
```
function/S TextWaveToStrArray(w)
	wave/t w	
	string list, checkStr, escapedStr
	variable i=0
	
	wfprintf list, "\"%s\";", w	// semicolon-separated list
	for(i=0;i<itemsinlist(list,";");i+=1)
		checkStr = stringfromlist(i,list,";")
		if(countQuotes(checkStr)>2)	
			escapedStr = escapeInnerQuotes(checkStr)
			list = removelistitem(i,list,";")
			list = addlistitem(escapedStr,list,";",i)
		endif
	endfor
	return "["+list[0,strlen(list)-2]+"]"
end

function/s escapeInnerQuotes(str)
	string str
	variable i, escaped
	string dummy="", newStr=""
	
	for(i=1; i<strlen(str)-1; i+=1)
	
		// check if the current character is escaped
		if(cmpStr(str[i-1], "\\") == 0)
			escaped = 1
		else
			escaped = 0
		endif
	
		// find extra quotes
		dummy = str[i]
		if(cmpStr(dummy, "\"" ) == 0 && escaped == 0)
			dummy = "\\"+dummy
		endif
		newStr = newStr+dummy
	endfor
	return newStr
end
```

I've added some code to your `TextWaveToStrArray`.  
The remaining problem has to do with commas. Your code splits `values` by commas, which then becomes a problem if one has a script like this one: `getLS370temp("mc",max_age=10)`!  
I've tried to replace all value seperator commas with semicolons, but it doesn't quite work.

**Comment by Chrede88** [comment]
Yep! Can’t remember the name.

**Comment by Chrede88** [comment]
The branch is "new_JSON". I think I got everything working:)  
I've kept some of your original functions, no need to rewrite the stuff that creates the config files.
I still need to test it.

**Comment by Chrede88** [comment]
See #74
