### ISSUE TITLE
use data folders for instrument drivers to cleanup namespace

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#73]
To avoid having to worry about having unique names for any waves/variables for instrument drivers, we can use datafolders to hold the relevant variables for each instrument. I think this could really improve the readability of our driver code. No more need for things like `ips_wavename` it could just be `wavename` in the `ips` data folder.

**Comment by Chrede88** [comment]
Not a bad idea 👍  
I guess it's only needed for drivers with GUI windows.

**Comment by nikhartman** [comment]
Still think this is a good idea.
