### ISSUE TITLE
ReplaceBullets() broken

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#83]
This function lives in `ScanController.ipf`. Its only purpose is to replace the bullet points that start each line in the Igor history with `>>>`, because bullet points are weird cross-platform.

 It doesn't work anymore and that annoys me greatly.

**Comment by Chrede88** [comment]
Why do you think it doesn't work anymore?
Just tested it with `•bla bla`. It returns `>>> bla bla`.

**Comment by nikhartman** [comment]
Fix by removing it. Who cares.
