### ISSUE TITLE
sc_logstr cannot be added to .config files due to JSON trouble

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#84]
A log string that contains quotes like `getSlackNotice("nik.hartman")` will note write to/load from a JSON-formatted `.config` file correctly.

It's a real ugly problem.

**Comment by nikhartman** [comment]
Did we fix this? I feel like we did. @Chrede88 ?

**Comment by Chrede88** [comment]
Pretty sure we did.
