### ISSUE TITLE
babydac custom window will not update multiple channels

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#85]
Here is the situation... 2 custom DAC channels defined, try to update both from the window, only the first one updates.

```
CH1: -100
sm_plng: -200
CH3: -100
bg_plng: -200
```
Change `sm_plng: -250` and `bg_plng: -250`, hit the `Ramp` button, only `sm_plng` ramps.

This isn't a huge problem, but it is inconsistent with the standard DAC window.

**Comment by Chrede88** [comment]
Pretty, sure I fixed this inconsistency.

**Comment by nikhartman** [comment]
We should test it out. Last I remember it didn't work, but that could be
old information.

**Comment by Chrede88** [comment]
I haven't fixed that. It's not necessarily trivial to fix! If `bg_plng` depends on a channel that was changed by `sm_plng` then everything gets all fucked up. I think that was why I didn't "fixed" that problem.

**Comment by Chrede88** [comment]
I'm happy to fix it, if someone can some up with a solution.
