### ISSUE TITLE
Setting babyDAC channel to NaN outputs full scale

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#86]
Adam unfortunately found this bug with my Kondo device.

If you call `setOutputBD(instrID, 0, NaN)` the BabyDAC channel `0` will be set to its lowest limit, ignoring any software limits defined. In Adam's case, this meant instantly setting the voltage on a few gates to -5V, and killing the device.

Yikes.

**Comment by Chrede88** [comment]
Fucking hell! Yet another check is needed. Igor can check for NaN, so should be an easy fix.

**Comment by nikhartman** [comment]
Maybe make it a check for NaN and INF? Is INF a thing in Igor?

**Comment by Chrede88** [comment]
Yep! :+1:

**Comment by Chrede88** [comment]
See #87
