### ISSUE TITLE
Incorporate NAN/INF checks in all drivers

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#88]
We should incorporate NAN/INF checks in all `set` functions across all instruments drivers.  
Igor has a convenient function: `numtype(num)` which returns 0 if num is not NAN or INF. It returns 1 if num is NAN and 2 if it's INF.

**Comment by nikhartman** [comment]
This seems like a good idea. 

The reason it came up for Adam was he accidentally set `numpnts=1` in a sweep, which leads to `setpoint=NaN`. That's something that could happen anywhere, and who knows what the rest of the instruments might do if they are passed NaN.

**Comment by Chrede88** [comment]
See #89
