### ISSUE TITLE
Async warning printed every time

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#90]
When running `InitializeWaves`, the async setup/check function (`sc_findAsyncMeasurements`) is called every time. This function prints a warning if less than two instruments are setup for async collection. This is all good, but it also prints this warning, if I'm not doing any async collection at all!  
The quick fix is to change the if statement from
```
if(instrAsync<2)
    print waring
endif
```
to
```
if(instrAsync==1)
    print waring
endif
```

But it seems a little silly to call `sc_findAsyncMeasurements` in the first place, when non of the async boxes are checked.

I suggest leaving `sc_findAsyncMeasurements` as it is and wrapping the call to `sc_findAsyncMeasurements` in the following if statement:

```
if(sum(sc_measAsync)>0)
    sc_findAsyncMeasurements()
endif
```

**Comment by nikhartman** [comment]
I think I fixed this in the experiment I ran recently, same as your first suggestion. But, I like your second idea better. Go for it.

**Comment by nikhartman** [comment]
Fixed
