### ISSUE TITLE
K2400 voltage reading

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#91]
When the Keithley is in voltage (source) mode and current (sense) mode, requesting the voltage returns some useless small number. I'm guessing it's the same problem for current readings if the source and sense modes are current and voltage.
This is an issue if one wants to ramp a voltage! The first call in `rampK2400voltage` is `getk2400voltage` in order to figure out which way the ramp is going and how far.
The bug will make the K2400 jump to almost zero every time regardless of the current output voltage!!

I'm not sure how to fix this!

**Comment by nikhartman** [comment]
Clear buffer? Make sure it is in the correct COM mode?

**Comment by nikhartman** [comment]
Closing this until we can prove it is a consistent problem.
