### ISSUE TITLE
copy hdf5 file to server results in corruption (does not happen on local copy)

### ISSUE THREAD

**Issue by nikhartman** [folk-lab/IgorAcq#98]
To backup data files I am using Igor's `CopyFile` command. If I copy an `hdf5` file from somewhere on the local disk to another location on the local disk, there is no problem. Copying from the local disk to the mounted `measurement-data` folder from `qdot-server` results in a copy in `measurement-data` that is corrupt and unreadable.

What the hell?!

**Comment by Chrede88** [comment]
Alternatively, just write the file twice! It's not going to add any significant overhead on the code.

**Comment by nikhartman** [comment]
Fixed in #103
